---
spring:
  application:
    name: audittrailsapi
  profiles:
    active: development
  config:
    import: optional:configserver:https://audittrails.tingg.africa/configserver
  rabbitmq:
    host: 10.250.20.62
    port: 5672
    username: audits-mq-user
    password: jakababa.2022
    template:
      retry:
        routing-key: audit-trails-retry
      routing-key: audit-trails
      username: audits-mq-user
      virtual-host: AUDITS
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
    config:
      fail-fast: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
mq: mq.sandbox.mau.cellulant.com
Vhost: AUDITS_SBOX
user: audits-mq-user-sandbox
pwd: j@ka13aber.f1do